In [1]:
import ecmwf.data as ecdata
from magpye import GeoMap
from ecmwf.opendata import Client
import xarray as xr
import datetime
import numpy as np

In [2]:
client = Client("ecmwf")

In [7]:
dt = datetime.datetime.now()

# date = dt.strftime('%Y%m%d')
date = '20240514'
parameters = ['u', 'v']
filename = f'open-data/{date}.grib'
# step=[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69]
step=0

print(filename)

open-data/20240514.grib


In [8]:
client.retrieve(
    date=date,
    time=0,
    step=step,
    stream="oper",
    levelist=[1000],
    param=parameters,
    target=filename
)

HTTPError: 404 Client Error: Not Found for url: https://data.ecmwf.int/forecasts/20240514/00z/ifs/0p25/oper/20240514000000-0h-oper-fc.index

In [5]:
ds = xr.open_dataset(filename)

In [6]:
ds

<xarray.Dataset> Size: 199MB
Dimensions:        (step: 24, latitude: 721, longitude: 1440)
Coordinates:
    time           datetime64[ns] 8B ...
  * step           (step) timedelta64[ns] 192B 0 days 00:00:00 ... 2 days 21:...
    isobaricInhPa  float64 8B ...
  * latitude       (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude      (longitude) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
    valid_time     (step) datetime64[ns] 192B ...
Data variables:
    u              (step, latitude, longitude) float32 100MB ...
    v              (step, latitude, longitude) float32 100MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2024-05-17T22:26 GRIB to CDM+CF via cfgrib-0.9.1...

In [7]:
ds['u']

<xarray.DataArray 'u' (step: 24, latitude: 721, longitude: 1440)> Size: 100MB
[24917760 values with dtype=float32]
Coordinates:
    time           datetime64[ns] 8B ...
  * step           (step) timedelta64[ns] 192B 0 days 00:00:00 ... 2 days 21:...
    isobaricInhPa  float64 8B ...
  * latitude       (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude      (longitude) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
    valid_time     (step) datetime64[ns] 192B ...
Attributes: (12/29)
    GRIB_paramId:                             131
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      1038240
    GRIB_typeOfLevel:                         isobaricInhPa
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_name:                                U component of wind
    GRIB_shortName:                           u
    GRIB_units:                               m s**-1
    long_name:                                U component of wind
    units:                                    m s**-1
    standard_name:                            eastward_wind

In [25]:
lat = ds['latitude'].values
lon = ds['longitude'].values

In [28]:
print(np.where(lat == 20))
print(np.where(lat == -20))
print(np.where(lon == 80))
print(np.where(lon == 160))

(array([280], dtype=int64),)
(array([440], dtype=int64),)
(array([1040], dtype=int64),)
(array([1360], dtype=int64),)


In [24]:
lat[280:441]

array([ 20.  ,  19.75,  19.5 ,  19.25,  19.  ,  18.75,  18.5 ,  18.25,
        18.  ,  17.75,  17.5 ,  17.25,  17.  ,  16.75,  16.5 ,  16.25,
        16.  ,  15.75,  15.5 ,  15.25,  15.  ,  14.75,  14.5 ,  14.25,
        14.  ,  13.75,  13.5 ,  13.25,  13.  ,  12.75,  12.5 ,  12.25,
        12.  ,  11.75,  11.5 ,  11.25,  11.  ,  10.75,  10.5 ,  10.25,
        10.  ,   9.75,   9.5 ,   9.25,   9.  ,   8.75,   8.5 ,   8.25,
         8.  ,   7.75,   7.5 ,   7.25,   7.  ,   6.75,   6.5 ,   6.25,
         6.  ,   5.75,   5.5 ,   5.25,   5.  ,   4.75,   4.5 ,   4.25,
         4.  ,   3.75,   3.5 ,   3.25,   3.  ,   2.75,   2.5 ,   2.25,
         2.  ,   1.75,   1.5 ,   1.25,   1.  ,   0.75,   0.5 ,   0.25,
         0.  ,  -0.25,  -0.5 ,  -0.75,  -1.  ,  -1.25,  -1.5 ,  -1.75,
        -2.  ,  -2.25,  -2.5 ,  -2.75,  -3.  ,  -3.25,  -3.5 ,  -3.75,
        -4.  ,  -4.25,  -4.5 ,  -4.75,  -5.  ,  -5.25,  -5.5 ,  -5.75,
        -6.  ,  -6.25,  -6.5 ,  -6.75,  -7.  ,  -7.25,  -7.5 ,  -7.75,
      

In [29]:
lon[1040:1361]

array([ 80.  ,  80.25,  80.5 ,  80.75,  81.  ,  81.25,  81.5 ,  81.75,
        82.  ,  82.25,  82.5 ,  82.75,  83.  ,  83.25,  83.5 ,  83.75,
        84.  ,  84.25,  84.5 ,  84.75,  85.  ,  85.25,  85.5 ,  85.75,
        86.  ,  86.25,  86.5 ,  86.75,  87.  ,  87.25,  87.5 ,  87.75,
        88.  ,  88.25,  88.5 ,  88.75,  89.  ,  89.25,  89.5 ,  89.75,
        90.  ,  90.25,  90.5 ,  90.75,  91.  ,  91.25,  91.5 ,  91.75,
        92.  ,  92.25,  92.5 ,  92.75,  93.  ,  93.25,  93.5 ,  93.75,
        94.  ,  94.25,  94.5 ,  94.75,  95.  ,  95.25,  95.5 ,  95.75,
        96.  ,  96.25,  96.5 ,  96.75,  97.  ,  97.25,  97.5 ,  97.75,
        98.  ,  98.25,  98.5 ,  98.75,  99.  ,  99.25,  99.5 ,  99.75,
       100.  , 100.25, 100.5 , 100.75, 101.  , 101.25, 101.5 , 101.75,
       102.  , 102.25, 102.5 , 102.75, 103.  , 103.25, 103.5 , 103.75,
       104.  , 104.25, 104.5 , 104.75, 105.  , 105.25, 105.5 , 105.75,
       106.  , 106.25, 106.5 , 106.75, 107.  , 107.25, 107.5 , 107.75,
      